openapi: 3.0.1
info:
  title: products API
  description: Product microservice
  version: 2.6.6
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /update:
    put:
      tags:
        - product-controller
      operationId: updateProduct
      parameters:
        - name: product
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
  /addProducts:
    post:
      tags:
        - product-controller
      operationId: addNewProducts
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: OK
  /addProduct:
    post:
      tags:
        - product-controller
      operationId: addNewProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: OK
  /products:
    get:
      tags:
        - product-controller
      operationId: allProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /productById/{id}:
    get:
      tags:
        - product-controller
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Product'
  /deleteById/{id}:
    delete:
      tags:
        - product-controller
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        price:
          type: integer
          format: int64
